version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    binary: kube-cluster-binpacking-exporter

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE*
      - README*

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

# ── Docker images (multi-arch via buildx) ────────────────────────────────
dockers:
  - image_templates:
      - "ghcr.io/sherifabdlnaby/kube-cluster-binpacking-exporter:{{ .Version }}-amd64"
    use: buildx
    goarch: amd64
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/sherifabdlnaby/kube-cluster-binpacking-exporter"

  - image_templates:
      - "ghcr.io/sherifabdlnaby/kube-cluster-binpacking-exporter:{{ .Version }}-arm64"
    use: buildx
    goarch: arm64
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/sherifabdlnaby/kube-cluster-binpacking-exporter"

# ── Multi-arch manifest lists ────────────────────────────────────────────
docker_manifests:
  - name_template: "ghcr.io/sherifabdlnaby/kube-cluster-binpacking-exporter:{{ .Version }}"
    image_templates:
      - "ghcr.io/sherifabdlnaby/kube-cluster-binpacking-exporter:{{ .Version }}-amd64"
      - "ghcr.io/sherifabdlnaby/kube-cluster-binpacking-exporter:{{ .Version }}-arm64"

  - name_template: "ghcr.io/sherifabdlnaby/kube-cluster-binpacking-exporter:{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "ghcr.io/sherifabdlnaby/kube-cluster-binpacking-exporter:{{ .Version }}-amd64"
      - "ghcr.io/sherifabdlnaby/kube-cluster-binpacking-exporter:{{ .Version }}-arm64"

  - name_template: "ghcr.io/sherifabdlnaby/kube-cluster-binpacking-exporter:latest"
    image_templates:
      - "ghcr.io/sherifabdlnaby/kube-cluster-binpacking-exporter:{{ .Version }}-amd64"
      - "ghcr.io/sherifabdlnaby/kube-cluster-binpacking-exporter:{{ .Version }}-arm64"

# ── Changelog ────────────────────────────────────────────────────────────
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Performance Improvements
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Refactors
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: Others
      order: 999

# ── GitHub Release ───────────────────────────────────────────────────────
release:
  github:
    owner: sherifabdlnaby
    name: kube-cluster-binpacking-exporter
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## Kubernetes Cluster Binpacking Exporter {{.Tag}}

    Prometheus exporter for monitoring Kubernetes cluster binpacking efficiency.

    ### Container Images

    Multi-arch Docker images available on GitHub Container Registry:
    ```bash
    docker pull ghcr.io/sherifabdlnaby/kube-cluster-binpacking-exporter:{{.Tag}}
    ```

    Supported platforms: `linux/amd64`, `linux/arm64`

    ### Helm Chart

    Helm chart published to OCI registry:
    ```bash
    # Install from OCI registry
    helm install binpacking-exporter \
      oci://ghcr.io/sherifabdlnaby/charts/kube-cluster-binpacking-exporter \
      --version {{.Version}}

    # Or with custom values
    helm install binpacking-exporter \
      oci://ghcr.io/sherifabdlnaby/charts/kube-cluster-binpacking-exporter \
      --version {{.Version}} \
      --set debug=true \
      --set resyncPeriod=1m
    ```

  footer: |
    **Full Changelog**: https://github.com/sherifabdlnaby/kube-cluster-binpacking-exporter/compare/{{.PreviousTag}}...{{.Tag}}

    ---

    ### Installation

    **Helm (Recommended):**
    ```bash
    helm install binpacking-exporter \
      oci://ghcr.io/sherifabdlnaby/charts/kube-cluster-binpacking-exporter \
      --version {{.Version}}
    ```

    **Binary:**
    Download the appropriate binary for your platform from the assets above.

    **Docker:**
    ```bash
    docker run -v ~/.kube/config:/kubeconfig:ro \
      ghcr.io/sherifabdlnaby/kube-cluster-binpacking-exporter:{{.Tag}} \
      --kubeconfig=/kubeconfig
    ```
