version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    binary: kube-binpacking-exporter

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - LICENSE*
      - README*

checksum:
  name_template: 'checksums.txt'

# ── Docker (multi-arch via buildx) ─────────────────────────────────────
# Uses GoReleaser's pre-built binaries — no QEMU compilation needed for ARM.
# Dockerfile.release just COPYs the binary into distroless.
# The original Dockerfile (multi-stage, builds from source) is kept for local use.
dockers_v2:
  - dockerfile: Dockerfile.release
    images:
      - "ghcr.io/sherifabdlnaby/kube-binpacking-exporter"
    tags:
      - "{{ .Version }}"
      - "{{ .Major }}.{{ .Minor }}"
    platforms:
      - linux/amd64
      - linux/arm64
    annotations:
      "org.opencontainers.image.title": "{{ .ProjectName }}"
      "org.opencontainers.image.description": "Prometheus exporter for Kubernetes binpacking efficiency"
    labels:
      "org.opencontainers.image.title": "{{ .ProjectName }}"
      "org.opencontainers.image.description": "Prometheus exporter for Kubernetes binpacking efficiency"
      "org.opencontainers.image.version": "{{ .Version }}"
      "org.opencontainers.image.source": "{{ .GitURL }}"
      "org.opencontainers.image.licenses": "MIT"
      "org.opencontainers.image.created": "{{ .Date }}"
      "org.opencontainers.image.revision": "{{ .FullCommit }}"

# ── Cosign signing ─────────────────────────────────────────────────────
# Keyless signing via GitHub OIDC — signs Docker images and binary checksums
docker_signs:
  - cmd: cosign
    artifacts: all
    args: ["sign", "--yes", "${artifact}"]

signs:
  - cmd: cosign
    artifacts: checksum
    args: ["sign-blob", "--yes", "--output-signature=${signature}", "${artifact}"]

# ── SBOM generation ────────────────────────────────────────────────────
# Syft generates SBOMs for each archive — attached to the GitHub Release
sboms:
  - artifacts: archive

snapshot:
  version_template: "{{ incpatch .Version }}-next"

# ── Changelog ────────────────────────────────────────────────────────────
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - '^build:'
      - Merge pull request
      - Merge branch
  groups:
    - title: Breaking Changes
      regexp: '^.*?\w+(\(.+\))?!:.+$'
      order: 0
    - title: New Features
      regexp: '^.*?feat(\(.+\))?:.+$'
      order: 100
    - title: Security
      regexp: '^.*?sec(\(.+\))?:.+$'
      order: 150
    - title: Bug Fixes
      regexp: '^.*?(fix|refactor)(\(.+\))?:.+$'
      order: 200
    - title: Performance
      regexp: '^.*?perf(\(.+\))?:.+$'
      order: 300
    - title: Other
      order: 999

# ── GitHub Release ───────────────────────────────────────────────────────
release:
  github:
    owner: sherifabdlnaby
    name: kube-binpacking-exporter
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## `{{.Tag}}` 🚀

  footer: |
    **Full Changelog**: https://github.com/sherifabdlnaby/kube-binpacking-exporter/compare/{{.PreviousTag}}...{{.Tag}}

    ---

    ### Installation

    **Helm (Recommended):**
    ```bash
    helm install kube-binpacking-exporter \
      oci://ghcr.io/sherifabdlnaby/charts/kube-binpacking-exporter \
      --version {{.Version}}
    ```

    **Binary:**
    Download the appropriate binary for your platform from the assets below.

    **Docker:**
    ```bash
    docker run -v ~/.kube/config:/kubeconfig:ro \
      ghcr.io/sherifabdlnaby/kube-binpacking-exporter:{{.Tag}} \
      --kubeconfig=/kubeconfig
    ```

    **Verify image signature:**
    ```bash
    cosign verify \
      --certificate-oidc-issuer=https://token.actions.githubusercontent.com \
      --certificate-identity-regexp="https://github.com/sherifabdlnaby/kube-binpacking-exporter/.*" \
      ghcr.io/sherifabdlnaby/kube-binpacking-exporter:{{.Tag}}
    ```