version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    binary: kube-cluster-binpacking-exporter

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - LICENSE*
      - README*

checksum:
  name_template: 'checksums.txt'

# ── Docker images (one per arch) ───────────────────────────────────────
# GoReleaser builds each arch separately, then docker_manifests joins them.
# Uses the existing multi-stage Dockerfile (builds from source inside Docker).
dockers:
  - image_templates:
      - "ghcr.io/sherifabdlnaby/kube-cluster-binpacking-exporter:{{ .Version }}-amd64"
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--build-arg=VERSION={{ .Version }}"
      - "--build-arg=COMMIT={{ .FullCommit }}"
      - "--build-arg=DATE={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
    extra_files:
      - go.mod
      - go.sum
      - Makefile
      - main.go
      - collector.go
      - kubernetes.go
      - leaderelection.go
    goos: linux
    goarch: amd64

  - image_templates:
      - "ghcr.io/sherifabdlnaby/kube-cluster-binpacking-exporter:{{ .Version }}-arm64"
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--build-arg=VERSION={{ .Version }}"
      - "--build-arg=COMMIT={{ .FullCommit }}"
      - "--build-arg=DATE={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
    extra_files:
      - go.mod
      - go.sum
      - Makefile
      - main.go
      - collector.go
      - kubernetes.go
      - leaderelection.go
    goos: linux
    goarch: arm64

# ── Multi-arch manifests ───────────────────────────────────────────────
# Creates the tags consumers actually pull (version + major.minor)
docker_manifests:
  - name_template: "ghcr.io/sherifabdlnaby/kube-cluster-binpacking-exporter:{{ .Version }}"
    image_templates:
      - "ghcr.io/sherifabdlnaby/kube-cluster-binpacking-exporter:{{ .Version }}-amd64"
      - "ghcr.io/sherifabdlnaby/kube-cluster-binpacking-exporter:{{ .Version }}-arm64"
  - name_template: "ghcr.io/sherifabdlnaby/kube-cluster-binpacking-exporter:{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "ghcr.io/sherifabdlnaby/kube-cluster-binpacking-exporter:{{ .Version }}-amd64"
      - "ghcr.io/sherifabdlnaby/kube-cluster-binpacking-exporter:{{ .Version }}-arm64"

# ── Cosign signing ─────────────────────────────────────────────────────
# Keyless signing via GitHub OIDC — signs Docker manifests and binary checksums
docker_signs:
  - cmd: cosign
    artifacts: manifests
    args: ["sign", "--yes", "${artifact}"]

signs:
  - cmd: cosign
    artifacts: checksum
    args: ["sign-blob", "--yes", "--output-signature=${signature}", "${artifact}"]

# ── SBOM generation ────────────────────────────────────────────────────
# Syft generates SBOMs for each archive — attached to the GitHub Release
sboms:
  - artifacts: archive

snapshot:
  version_template: "{{ incpatch .Version }}-next"

# ── Changelog ────────────────────────────────────────────────────────────
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - '^build:'
      - Merge pull request
      - Merge branch
  groups:
    - title: Breaking Changes
      regexp: '^.*?\w+(\(.+\))?!:.+$'
      order: 0
    - title: New Features
      regexp: '^.*?feat(\(.+\))?:.+$'
      order: 100
    - title: Security
      regexp: '^.*?sec(\(.+\))?:.+$'
      order: 150
    - title: Bug Fixes
      regexp: '^.*?(fix|refactor)(\(.+\))?:.+$'
      order: 200
    - title: Performance
      regexp: '^.*?perf(\(.+\))?:.+$'
      order: 300
    - title: Other
      order: 999

# ── GitHub Release ───────────────────────────────────────────────────────
release:
  github:
    owner: sherifabdlnaby
    name: kube-cluster-binpacking-exporter
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## `{{.Tag}}` 🚀

  footer: |
    **Full Changelog**: https://github.com/sherifabdlnaby/kube-cluster-binpacking-exporter/compare/{{.PreviousTag}}...{{.Tag}}

    ---

    ### Installation

    **Helm (Recommended):**
    ```bash
    helm install binpacking-exporter \
      oci://ghcr.io/sherifabdlnaby/charts/kube-cluster-binpacking-exporter \
      --version {{.Version}}
    ```

    **Binary:**
    Download the appropriate binary for your platform from the assets below.

    **Docker:**
    ```bash
    docker run -v ~/.kube/config:/kubeconfig:ro \
      ghcr.io/sherifabdlnaby/kube-cluster-binpacking-exporter:{{.Tag}} \
      --kubeconfig=/kubeconfig
    ```

    **Verify image signature:**
    ```bash
    cosign verify \
      --certificate-oidc-issuer=https://token.actions.githubusercontent.com \
      --certificate-identity-regexp="https://github.com/sherifabdlnaby/kube-cluster-binpacking-exporter/.*" \
      ghcr.io/sherifabdlnaby/kube-cluster-binpacking-exporter:{{.Tag}}
    ```